language: node_js
sudo: required
dist: trusty
addons:
    chrome: stable
before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
cache:
  directories:
    - ~/.npm
notifications:
  email: false

after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
stages:
  - basic test
  - additional tests
jobs:
  fail_fast: true
  include:
  - stage: basic test
    node_js: '10'
  - stage: additional tests
    node_js: '9'
  - node_js: '8'